# Lab 1: More on Data Manipulation Tools for Data Science with Python

In this lab, you will learn and gain hands-on experience on the use of Numpy for numerical computation and Pandas for data manipulation.

Follow the instruction and run the code cells. Make sure you understand what happens in every stage. <br>

<b>Helpful Links:</b>

  https://docs.scipy.org/doc/numpy/reference/
  
  https://docs.scipy.org/doc/scipy/reference/
  
  https://pandas.pydata.org/pandas-docs/stable/reference/index.html
  
  http://www.utc.fr/~jlaforet/Suppl/python-cheatsheets.pdf


## More on Numerical Python (Numpy)

Numpy is a popular python library mainly used for working with numerical data in Python. A common data sctructure in numpy is multidimensional array. Think of a 1-D array as a python list e.g `[1, 2, 3, 4]`






Numpy is already installed in Google Colab, you can simple import for use. The most common alias used for importing numpy is `np`.

In [1]:
import typing

import numpy as np
import numpy.typing as npt

### Creating Numpy Arrays

We can create a numpy array from a python list as follows:

In [2]:
my_1D_arr = np.array([1, 2, 3, 4, 5])
my_1D_arr

array([1, 2, 3, 4, 5])

Numpy arrays have dimensions. The array created above is a one dimensinal array because it has only one dimension.

We can also have 2 dimensional array.

Think of 2-D array as matrix in mathematics:

$$\begin{bmatrix}
    x_{11} & x_{12} & x_{13} & \dots  & x_{1n} \\
    x_{21} & x_{22} & x_{23} & \dots  & x_{2n} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    x_{d1} & x_{d2} & x_{d3} & \dots  & x_{dn}
\end{bmatrix}$$

Creating a 2D array from a list of lists. Two dimensional arrays must be rectangular.

In [3]:
my_2D_arr = np.array([[7, 1, 4], [5, 5, 9], [0, 8, 3], [2, 6, 2]])

my_2D_arr

array([[7, 1, 4],
       [5, 5, 9],
       [0, 8, 3],
       [2, 6, 2]])

We can have higher dimensional arrays e.g. 3-D array.

In [4]:
np.array([1, 2, 4, 3, 7, 4, 2, 2, 9, 0, 7, 5, 1, 9, 3, 5, 0, 2, 9, 8, 6, 5, 9, 8]).reshape(4, 3, 2)

array([[[1, 2],
        [4, 3],
        [7, 4]],

       [[2, 2],
        [9, 0],
        [7, 5]],

       [[1, 9],
        [3, 5],
        [0, 2]],

       [[9, 8],
        [6, 5],
        [9, 8]]])

The example 3-D array above for better understanding is displayed as a cuboid (rightmost image) below:

![](https://forums.fast.ai/uploads/default/original/3X/5/9/59cf148e07e912812cadb12eafb0afcc7edb250e.jpeg)

In [5]:
# creating a 3x2x3 3D array
my_3D_arr = np.array([
    [[7, 1, 4], [5, 5, 9]],
    [[0, 8, 3], [2, 6, 2]],
    [[10, 0, -1], [8, -2, 4]]
    ])

my_3D_arr

array([[[ 7,  1,  4],
        [ 5,  5,  9]],

       [[ 0,  8,  3],
        [ 2,  6,  2]],

       [[10,  0, -1],
        [ 8, -2,  4]]])

### Common Numpy Array Attributes

Checking the shape, size, and length of an array -- common numpy array attributes

In [6]:
print(f"Shape of my_1D_arr is: {my_1D_arr.shape}")
print(f"Shape of my_2D_arr is: {my_2D_arr.shape}")
print(f"Shape of my_3D_arr is: {my_3D_arr.shape}")

Shape of my_1D_arr is: (5,)
Shape of my_2D_arr is: (4, 3)
Shape of my_3D_arr is: (3, 2, 3)


In [7]:
print(f"Size of my_1D_arr is: {my_1D_arr.size}")
print(f"Size of my_2D_arr is: {my_2D_arr.size}")
print(f"Size of my_3D_arr is: {my_3D_arr.size}")

Size of my_1D_arr is: 5
Size of my_2D_arr is: 12
Size of my_3D_arr is: 18


In [8]:
print(f"Length of my_1D_arr is: {len(my_1D_arr)}")
print(f"Length of my_2D_arr is: {len(my_2D_arr)}")
print(f"Length of my_3D_arr is: {len(my_3D_arr)}")

Length of my_1D_arr is: 5
Length of my_2D_arr is: 4
Length of my_3D_arr is: 3


What difference(s) did you notice?

Data Types (dtype): Numpy array elements have the same data type.

In [9]:
my_1D_arr.dtype

dtype('int64')

Creating an array with 'float64'. The presence of 'float64' data type in the midst of integer data type will force numpy to store all elements of the array as 'float64' data type.

In [10]:
my_1D_arr_2 = np.array([1, 3.0, 2])
my_1D_arr_2.dtype

dtype('float64')

Creating an array with string dtype. The presence of a string data type in the midst of integer data type will force numpy to store all elements of the array as string data type.

In [11]:
np.array([1, "hello ", "I am learning data science", 3]).dtype

dtype('<U26')

You can also specify the data type of an array when creating the array.


In [12]:
my_1D_arr_float = np.array([1, 2, 3, 4, 5], dtype=np.float64)
print(my_1D_arr_float.dtype)
my_1D_arr_float

float64


array([1., 2., 3., 4., 5.])

Object datatype: each element of the array is essentially a pointer to a Python object. This flexibility allows you to create arrays that can hold elements of different data types and structures.

In [13]:
object_dtype_arr = np.array([[2, "hello", {1, 2, 3}]])
print(object_dtype_arr.dtype)

object


non-rectangular array: numpy 2-D arrays must be rectangular (or square). An attempt to create a non rectangular 2-D array will force numpy to store it as a 1-D array of type object.

In [14]:
non_rectangular = np.array([[1, 2], [3, 4, 5], [6, 7, 8, 9]])
non_rectangular

<ipython-input-14-a1f4220054cf>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  non_rectangular = np.array([[1, 2], [3, 4, 5], [6, 7, 8, 9]])


array([list([1, 2]), list([3, 4, 5]), list([6, 7, 8, 9])], dtype=object)

In [15]:
print(f"Shape of non_rectangular is: {non_rectangular.shape}")
print(f"Dtype of non_rectangular is: {non_rectangular.dtype}")

Shape of non_rectangular is: (3,)
Dtype of non_rectangular is: object


### Creating variety of arrays with NumPy's functions.

Creating array from a range of numbers

In [16]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

Creating array with equally spaced elements.

In [17]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Creating array with logarithmically spaced elements.

In [18]:
np.logspace(1, 10, 10)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

Creating an array with zeros

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Creating a diagonal array

In [20]:
np.diag([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

Creating an identity *matrix*

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.identity(5)  # same as using np.eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Common Methods of a Numpy Array

sort, argsort, sum, max, mean, min, sine, cos, tan, log, exp, random.

First let's create a random array.

In [23]:
my_rand_arr = np.random.randint(low=0, high=9, size=10) # sample from a uniform distribution
my_rand_arr

array([2, 1, 8, 3, 1, 6, 5, 8, 5, 4])

The array created above is a non reproducible random array. Re-running the code cell will yield a different array.

To make a randomly generated numpy array reproducible, we need to set the value for the random seed.

In [24]:
np.random.seed(42) # set seed for reproducibility
my_rand_arr = np.random.randint(low=0, high=9, size=10) # sample from a uniform distribution
my_rand_arr

array([6, 3, 7, 4, 6, 2, 6, 7, 4, 3])

Sampling from a normal distribution

In [25]:
np.random.rand(5)

array([0.14286682, 0.65088847, 0.05641158, 0.72199877, 0.93855271])

Sampling from a list of choices

In [26]:
np.random.choice([1, 3, 5, 8, 2, 4], size=3, replace=False, p=None)

array([5, 4, 2])

In [27]:
print(f"before sorting, array is: {my_rand_arr}")
print(f"sorted array is: {np.sort(my_rand_arr)}") # returns a copy of the array after sorting it. Original array remains unchanged.
print(f"after sorting, array is: {my_rand_arr}")

before sorting, array is: [6 3 7 4 6 2 6 7 4 3]
sorted array is: [2 3 3 4 4 6 6 6 7 7]
after sorting, array is: [6 3 7 4 6 2 6 7 4 3]


`np.sort(my_rand_arr)` returns a copy of the array after sorting it. Original array remains unchanged.

Returning the indices that would sort an array.

In [28]:
my_rand_arr.argsort()

array([5, 1, 9, 3, 8, 0, 4, 6, 2, 7])

Using the indices above to sort the array

In [29]:
my_rand_arr[my_rand_arr.argsort()]

array([2, 3, 3, 4, 4, 6, 6, 6, 7, 7])

In [30]:
print(f"before sorting, array was: {my_rand_arr}")
my_rand_arr.sort() # returns None, but mutates the array by sorting it.
print(f"after sorting, array is: {my_rand_arr}")

before sorting, array was: [6 3 7 4 6 2 6 7 4 3]
after sorting, array is: [2 3 3 4 4 6 6 6 7 7]


`my_rand_arr.sort()` returns None, but mutates the array by sorting it.

Common aggregating functions

In [31]:
print(f"Sum of my_rand_arr is: {my_rand_arr.sum()}")
print(f"Mean of my_rand_arr is: {my_rand_arr.mean()}")
print(f"Standard Deviation of my_rand_arr is: {my_rand_arr.std()}")
print(f"Min of my_rand_arr is: {my_rand_arr.min()}")
print(f"Max of my_rand_arr is: {my_rand_arr.max()}")

Sum of my_rand_arr is: 48
Mean of my_rand_arr is: 4.8
Standard Deviation of my_rand_arr is: 1.7204650534085253
Min of my_rand_arr is: 2
Max of my_rand_arr is: 7


Remember, our example 2-D array is:

In [32]:
my_2D_arr

array([[7, 1, 4],
       [5, 5, 9],
       [0, 8, 3],
       [2, 6, 2]])

Aggregating the 2-D array

In [33]:
print(f"Sum of my_2D_arr is: {my_2D_arr.sum()}")
print(f"Mean of my_2D_arr is: {my_2D_arr.mean()}")
print(f"Min of my_2D_arr is: {my_2D_arr.min()}")
print(f"Max of my_2D_arr is: {my_2D_arr.max()}")

Sum of my_2D_arr is: 52
Mean of my_2D_arr is: 4.333333333333333
Min of my_2D_arr is: 0
Max of my_2D_arr is: 9


You can also aggregaate along a particular axis. E.g. along axis 0

In [34]:
print(f"Sum of my_2D_arr along axis 0 is: {my_2D_arr.sum(axis=0)}")
print(f"Mean of my_2D_arr along axis 0 is: {my_2D_arr.mean(axis=0)}")
print(f"Min of my_2D_arr along axis 0 is: {my_2D_arr.min(axis=0)}")
print(f"Max of my_2D_arr along axis 0 is: {my_2D_arr.max(axis=0)}")

Sum of my_2D_arr along axis 0 is: [14 20 18]
Mean of my_2D_arr along axis 0 is: [3.5 5.  4.5]
Min of my_2D_arr along axis 0 is: [0 1 2]
Max of my_2D_arr along axis 0 is: [7 8 9]


The same applies to axis 1.

*Exercise:* What do you think the sum, mean, min, and max values of `my_2D_arr` would be along axis 1? Write down the values and uncomment the code block below to confirm your answers.

In [35]:
# print(f"Sum of my_2D_arr along axis 1 is: {my_2D_arr.sum(axis=1)}")
# print(f"Mean of my_2D_arr along axis 1 is: {my_2D_arr.mean(axis=1)}")
# print(f"Min of my_2D_arr along axis 1 is: {my_2D_arr.min(axis=1)}")
# print(f"Max of my_2D_arr along axis 1 is: {my_2D_arr.max(axis=1)}")

Most numpy array's methods are also available as numpy fuctions. e.g. np.sort, np.argsort, np.max, np.min, np.mean.

Reshaping an array.

In [36]:
my_1D_arr_2 = np.arange(12)
my_1D_arr_2.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
my_1D_arr_2.reshape(-1, 2) # using -1 as the number of rows means as many rows as would be compactible with the given number of columns

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [38]:
my_2D_arr.reshape(-1) # flattens the array to a 1-D array. This can also be achieved using the .flatten or .ravel methods

array([7, 1, 4, 5, 5, 9, 0, 8, 3, 2, 6, 2])

### Arithmetic Operations

Numpy can broadcast (vectorize) most arithmetic operations over an array. Some common arithmetic operations:

In [39]:
print(f"my_rand_arr is: {my_rand_arr}")
print(f"Adding 2 to my_rand_arr gives: {my_rand_arr + 2}")
print(f"Subtracting 1 to my_rand_arr gives: {my_rand_arr - 1}")
print(f"Multiplying my_rand_arr by 3 gives: {my_rand_arr * 3}")
print(f"Dividing my_rand_arr by 2 gives: {my_rand_arr / 3}")
print(f"my_rand_arr modulo 2 gives:  {my_rand_arr % 2}")
print(f"my_rand_arr // 3 gives: {my_rand_arr // 3}")
print(f"Squaring my_rand_arr gives:  {my_rand_arr ** 2}")
print(f"my_rand_arr greater than 5? {my_rand_arr > 5}") # returns boolean array

my_rand_arr is: [2 3 3 4 4 6 6 6 7 7]
Adding 2 to my_rand_arr gives: [4 5 5 6 6 8 8 8 9 9]
Subtracting 1 to my_rand_arr gives: [1 2 2 3 3 5 5 5 6 6]
Multiplying my_rand_arr by 3 gives: [ 6  9  9 12 12 18 18 18 21 21]
Dividing my_rand_arr by 2 gives: [0.66666667 1.         1.         1.33333333 1.33333333 2.
 2.         2.         2.33333333 2.33333333]
my_rand_arr modulo 2 gives:  [0 1 1 0 0 0 0 0 1 1]
my_rand_arr // 3 gives: [0 1 1 1 1 2 2 2 2 2]
Squaring my_rand_arr gives:  [ 4  9  9 16 16 36 36 36 49 49]
my_rand_arr greater than 5? [False False False False False  True  True  True  True  True]


### More numpy functions


In [40]:
print(f"Log of 10 is: {np.log(10)}")
print(f"Log of each element of my_rand_arr is: {np.log(my_rand_arr)}")
print(f"Sine of each element of my_rand_arr is: {np.sin(my_rand_arr)}")
print(f"Exponent of each element of my_rand_arr is: {np.exp(my_rand_arr)}")
print(f"Exponent of each element of my_rand_arr rounded to 2 decimal place is: {np.round(np.exp(my_rand_arr), 2)}")

Log of 10 is: 2.302585092994046
Log of each element of my_rand_arr is: [0.69314718 1.09861229 1.09861229 1.38629436 1.38629436 1.79175947
 1.79175947 1.79175947 1.94591015 1.94591015]
Sine of each element of my_rand_arr is: [ 0.90929743  0.14112001  0.14112001 -0.7568025  -0.7568025  -0.2794155
 -0.2794155  -0.2794155   0.6569866   0.6569866 ]
Exponent of each element of my_rand_arr is: [   7.3890561    20.08553692   20.08553692   54.59815003   54.59815003
  403.42879349  403.42879349  403.42879349 1096.63315843 1096.63315843]
Exponent of each element of my_rand_arr rounded to 2 decimal place is: [   7.39   20.09   20.09   54.6    54.6   403.43  403.43  403.43 1096.63
 1096.63]


Applying custom function to elements of an array using `.vectorize` method.

In [41]:
def my_func(x: float) -> float:
    return 3*x**2 - 1

In [42]:
my_vectorized_func = np.vectorize(my_func)
my_vectorized_func(np.arange(5))

array([-1,  2, 11, 26, 47])

Stacking arrays

In [43]:
a = my_3D_arr.max(axis=0) # creating a 2-D aryay from my_3D_arr by taking the max value along axis 0
b = my_3D_arr.max(axis=1) # creating a 2-D aryay from my_3D_arr by taking the max value along axis 1
c = my_3D_arr.max(axis=2) # creating a 2-D aryay from my_3D_arr by taking the max value along axis 2

a # outputing array a

array([[10,  8,  4],
       [ 8,  6,  9]])

In [44]:
b # outputing array b

array([[ 7,  5,  9],
       [ 2,  8,  3],
       [10,  0,  4]])

In [45]:
# vertically stacking a and b
np.vstack([a, b])

array([[10,  8,  4],
       [ 8,  6,  9],
       [ 7,  5,  9],
       [ 2,  8,  3],
       [10,  0,  4]])

In [46]:
c # outputing array c

array([[ 7,  9],
       [ 8,  6],
       [10,  8]])

In [47]:
# horizontally stacking b and c
np.hstack([b, c])

array([[ 7,  5,  9,  7,  9],
       [ 2,  8,  3,  8,  6],
       [10,  0,  4, 10,  8]])

Useful functions for linear algebra

In [48]:
m = np.array([[1, 5], [3, 2]]) # sample 2x2 array to represent a matrix
v = np.array([[3], [-1]]) # sample 2x1 array to represent a vector

In [49]:
m

array([[1, 5],
       [3, 2]])

In [50]:
v

array([[ 3],
       [-1]])

In [51]:
# retrieving the main diagonal of a 2-D array.
np.diag(m)

array([1, 2])

Matrix multiplication

In [52]:
np.matmul(m, v)

array([[-2],
       [ 7]])

Matrix multiplication can also be done using '@'

In [53]:
m @ v

array([[-2],
       [ 7]])

Dot product


In [54]:
v1 = m[:, 1]
v1

array([5, 2])

In [55]:
np.dot(v1, v.flatten())

13

You can read Numpy's [official documentation](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html) for more information on how `.matmul` differs from `.dot`.

Tranposing an array

In [56]:
np.random.seed(0)
A = np.random.randint(low=0, high=9, size=(3, 3)) # sample 3x3 array
A

array([[5, 0, 3],
       [3, 7, 3],
       [5, 2, 4]])

transposing the array


In [57]:
A.transpose()

array([[5, 3, 5],
       [0, 7, 2],
       [3, 3, 4]])

transposing an array can also be achieved using the `.T` method


In [58]:
A.T

array([[5, 3, 5],
       [0, 7, 2],
       [3, 3, 4]])

Determinant of a 2-D numpy array

In [59]:
np.linalg.det(A)

23.00000000000001

Inverse of a 2-D rectangular array

In [60]:
np.linalg.inv(A)

array([[ 0.95652174,  0.26086957, -0.91304348],
       [ 0.13043478,  0.2173913 , -0.26086957],
       [-1.26086957, -0.43478261,  1.52173913]])

### Slicing and Filtering a Numpy Array

Slicing a numpy array is similar to slicing Python list.

In [61]:
print(f"my_rand_arr is: {my_rand_arr}")
print(f"First element of my_rand_arr is: {my_rand_arr[0]}")
print(f"Last element of my_rand_arr is: {my_rand_arr[-1]}")
print(f"First 3 elements of my_rand_arr is: {my_rand_arr[: 3]}")
print(f"Selecting only the first, third, and last element gives: {my_rand_arr[[0, 2, -1]]}")
print(f"Selecting all elements greater than 5 gives: {my_rand_arr[my_rand_arr > 5]}")

my_rand_arr is: [2 3 3 4 4 6 6 6 7 7]
First element of my_rand_arr is: 2
Last element of my_rand_arr is: 7
First 3 elements of my_rand_arr is: [2 3 3]
Selecting only the first, third, and last element gives: [2 3 7]
Selecting all elements greater than 5 gives: [6 6 6 7 7]


Slicing a 2-D array.

First, let's have a look at our original 2-D array.

In [62]:
my_2D_arr

array([[7, 1, 4],
       [5, 5, 9],
       [0, 8, 3],
       [2, 6, 2]])

In [63]:
print(f"Element in first row and third column is: {my_2D_arr[0, 2]}")
print(f"Elements in the second row are: {my_2D_arr[1]}") # notice that it returns a 1-D array
print(f"Elements in first 2 rows and in the second column are: {my_2D_arr[:2, 1]}") # notice that it returns a 1-D array
print(f"Elements in first 2 rows and in the second and third columns are: {my_2D_arr[:2, 1:3]}") # notice that it returns a 2-D array
print(f"Elements in first 2 rows and in the first and third columns are: {my_2D_arr[:2, [0, 2]]}") # notice that it returns a 2-D array


Element in first row and third column is: 4
Elements in the second row are: [5 5 9]
Elements in first 2 rows and in the second column are: [1 5]
Elements in first 2 rows and in the second and third columns are: [[1 4]
 [5 9]]
Elements in first 2 rows and in the first and third columns are: [[7 4]
 [5 9]]


Numpy array vs Python List. For loop vs vectorization.

In [64]:
def is_prime(x: int) -> bool:
    """Function to check if a number is prime"""

    if x < 2:
        return False
    elif x == 2:
        return True

    # checking if the number is not divisible by any number up to half the number
    return len([i for i in range(2, (x // 2) + 2) if x % i == 0]) == 0

In [65]:
def get_prime_numbers(n: int, is_prime_func: typing.Callable[[int], bool]=is_prime) -> list:
    """Function to return prime numbers up to n"""
    if int(n) == float(n) and n > 1: # checks if n is a whole number greater than one
        res =  [i for i in range(2, n+1) if is_prime_func(i)]
    return res

In [66]:
def numpy_is_prime(x: int) -> bool:
    """Function to check if a number is prime using numpy"""

    if x < 2:
        return False
    elif x == 2:
        return True

    # checking if the number is not divisible by any number up to half the number

    return (x % np.arange(2, (x // 2) + 2) == 0).sum() == 0

In [67]:
# using for-loop to generate prime numbers up to 20
get_prime_numbers(20)

[2, 3, 5, 7, 11, 13, 17, 19]

In [68]:
# using numpy array to generate prime numbers up to 20
get_prime_numbers(20, is_prime_func=numpy_is_prime)

[2, 3, 5, 7, 11, 13, 17, 19]

Comparing the runtime of generating prime numbers using for-loop vs using numpy array

In [69]:
import time

n = 30_000

# using for-loop
t0 = time.time()
prime_numbers = get_prime_numbers(n)
print(f"Prime numbers up to {n} generated with for-loop after: {time.time() - t0} secs")

# using numpy array
t0 = time.time()
numpy_prime_numbers = get_prime_numbers(n, is_prime_func=numpy_is_prime)
print(f"Prime numbers up to {n} generated with numpy array after: {time.time() - t0} secs")

# confirm if the result of using for-loop is same as using numpy array
assert (np.array(prime_numbers) != np.array(numpy_prime_numbers)).sum() == 0

Prime numbers up to 30000 generated with for-loop after: 28.868939876556396 secs
Prime numbers up to 30000 generated with numpy array after: 4.3824615478515625 secs


NumPy Arrays are faster than Python Lists because:
1. An array is a collection of homogeneous data-types that are stored in contiguous memory locations.
2. Python's list in is a collection of heterogeneous data types stored in non-contiguous memory locations.

Numpy arrays are great data structures for data science with python 😀.

## More to Pandas

Pandas is a python library that relies on NumPy to provide high-performance, easy-to-use data structures and data analysis tools. It come pre-installed in Google Colab. A popular alias for importing pandas is `pd`.



In [70]:
import pandas as pd

The primary tabular data structure in pandas is called a dataframe (df). Let's revisit pandas DataFrames.

### Pandas DataFrame

We often load DataFrames from a CSV file, but you can also create them from scratch. E.g from python list of lists.

In [71]:
# creating a dataframe from a list of lists
df = pd.DataFrame([[1, 2, 'cat'], [0, -1, "dog"], [4, 3, "bird"]])
print(df)

   0  1     2
0  1  2   cat
1  0 -1   dog
2  4  3  bird


Nicely display the dataframe when just outputing it (without using 'print' function) in a code cell.

In [72]:
df

0  1     2
0  1  2   cat
1  0 -1   dog
2  4  3  bird

Retrieving the index of the dataframe

In [73]:
list(df.index)

[0, 1, 2]

Retrieving the values of the dataframe. The values are returned as a numpy array. Why? Pandas is built on top of numpy.

In [74]:
df.values

array([[1, 2, 'cat'],
       [0, -1, 'dog'],
       [4, 3, 'bird']], dtype=object)

Retrieving the columns of the dataframe. Default column names are integers starting from 0 up to the number of columns - 1.

In [75]:
list(df.columns)

[0, 1, 2]

Setting the columns of the dataframe.

In [76]:
df.columns = ["A", "B", "C"]
df

A  B     C
0  1  2   cat
1  0 -1   dog
2  4  3  bird

Retreiving a column from the dataframe. It returns a pandas Series. You can also use `df.column_name` e.g. `df.A`

In [77]:
df['A']

0    1
1    0
2    4
Name: A, dtype: int64

Using double square brackets returns a DataFrame. The inner square bracket is a list.

In [78]:
df[['A']]

A
0  1
1  0
2  4

You can also retrieve more than one columns using double square brackets by listing more than one column names in the inner bracket.

In [79]:
df[['A', 'B']]

A  B
0  1  2
1  0 -1
2  4  3

`.loc` can also be used to retrieve part of a dataframe.

In [80]:
df.loc[0] # returns a the first row of the DataFrame which is a series too!

A      1
B      2
C    cat
Name: 0, dtype: object

Selecting a column using `.loc`

In [81]:
df.loc[:, 'A']

0    1
1    0
2    4
Name: A, dtype: int64

Returning a specific value if you specify the row and column labels

In [82]:
df.loc[1, "C"]

'dog'

`.iloc` can also be used with pandas dataframe.

In [83]:
df.iloc[2, 1:]

B       3
C    bird
Name: 2, dtype: object

**Pnadas DataFrame are rows and columns of Pandas Series**

### Pandas Series

Pandas Series is a pandas data structure that is the building block of dataframes. Think of a DataFrame as rows and columns of pandas Series. Numpy 1-D arrays and Pandas Series are analogous to python list and dictionary respectively.

Creating a Pandas Series

In [84]:
s = pd.Series([10, 3, 1, 5, 7, -2])
s

0    10
1     3
2     1
3     5
4     7
5    -2
dtype: int64

Retrieving the index of a series

In [85]:
list(s.index)

[0, 1, 2, 3, 4, 5]

Retreiving the values of the series, a numpy array is returned. Why? Pandas is built on top of numpy.

In [86]:
s.values

array([10,  3,  1,  5,  7, -2])

Arithemetic operations, filtering, and most operations are similar to those of numpy

In [87]:
s[s > 3] # filtering the series

0    10
3     5
4     7
dtype: int64

In [88]:
s.dtype # checking the data type

dtype('int64')

In [89]:
s.astype(float) # casting the dtype as float

0    10.0
1     3.0
2     1.0
3     5.0
4     7.0
5    -2.0
dtype: float64

````.astype```` method also works for numpy array

In [90]:
s.sort_values() # sorting the series by its values

5    -2
2     1
1     3
3     5
4     7
0    10
dtype: int64

In [91]:
s.sort_index(ascending=False) # sorting the series by its index

5    -2
4     7
3     5
2     1
1     3
0    10
dtype: int64

In [92]:
s.name # checking for the name of the series

The name of a Series becomes its index or column name if it is used to form a DataFrame. It is also used whenever displaying the Series using the interpreter.

In [93]:
s.name = "my series" # setting the Series name
s

0    10
1     3
2     1
3     5
4     7
5    -2
Name: my series, dtype: int64

In [94]:
s.name # checking the name atrribute after setting it.

'my series'

In [95]:
s.to_frame() # converting a Pandas Series to a DataFrame

my series
0         10
1          3
2          1
3          5
4          7
5         -2

Accessing elements of a Pandas Series

In [96]:
s[0] # using squared brackets just like in python's list

10

Using `.loc` to access elements of a series

In [97]:
s.loc[0] # access a group of rows, .loc[] is primarily label based, but may also be used with a boolean array.

10

Adding new elements to the series. If the index already exists, it updates its value

In [98]:
s.loc["new"] = 20 # loc can also be used to add a new element. index can be any immutable python data type
s

0      10
1       3
2       1
3       5
4       7
5      -2
new    20
Name: my series, dtype: int64

In [99]:
# s[-1] # throws key error. why? This is because using square brackets to access an element simply looks up the index and retrieve its value

In [100]:
s.loc[:2] # range of index labels

0    10
1     3
2     1
Name: my series, dtype: int64

In [101]:
s.iloc[-1] # iloc is interger indexing. works like conventional indexing in python list.

20

### More on Pandas DataFrames

Now that we have understood what pandas Series are and that a DataFrame is made up of rows and columns of Pandas Series, we will revisit DataFrames and learn more about them.

Adding a new row. Index and columns can be any immutable python data type


In [102]:
df.loc["new"] = [11, 5, "fish"]
df

A  B     C
0     1  2   cat
1     0 -1   dog
2     4  3  bird
new  11  5  fish

Adding a new column. Index and columns can be any immutable python data type


In [103]:
df["D"] = ["Ragdoll", "Golden Retriever", "Robin", "Bluefish"]
df

A  B     C                 D
0     1  2   cat           Ragdoll
1     0 -1   dog  Golden Retriever
2     4  3  bird             Robin
new  11  5  fish          Bluefish

Filtering the dataframe


Most operations on a DataFrame are operations on Series underneath the hood. E.g filtering.

In [104]:
df[df["B"] > 2]

A  B     C         D
2     4  3  bird     Robin
new  11  5  fish  Bluefish

In the above cell, `df["B"] > 2` is used to filter the dataframe `df` because it returns a boolean series as shown below:




In [105]:
df["B"] > 2

0      False
1      False
2       True
new     True
Name: B, dtype: bool

This boolean Series is then used to filter `df` by passing it to `df` as in `df[boolean series]`. The resulting DataFrame is a filter version of `df` with only rows where the boolean Series is `True`. As a result, a boolean Series to be used to filter a DataFrame must have the same length (number of rows) as the DataFrame. Also note that a boolean Series can also be used to filter a Series. Boolean Series are similar to mask in Numpy as they are both used for filtering.

Transforming a column: Derived column


In [106]:
df["A"] = df["A"] * 2
df

A  B     C                 D
0     2  2   cat           Ragdoll
1     0 -1   dog  Golden Retriever
2     8  3  bird             Robin
new  22  5  fish          Bluefish

Creating a data frame from a dictionary

In [107]:
df2 = pd.DataFrame(
    {
        'A': [2, 2, 8, 22, 6, 5],
        'B': [2, -1, 3, 5, 10, 4],
        'C': ['cat', 'dog', 'bird', 'dog', 'cat', 'fish'],
        'D': ['Ragdoll', 'Golden Retriever', 'Robin', 'Bulldog ', 'Bengal', 'Bluefish']
    },
    index=[11, 12, "three", -1,  10, 10] # you can also specify column names if you're passing list of lists to a DataFrame.
)

df2

A   B     C                 D
11      2   2   cat           Ragdoll
12      2  -1   dog  Golden Retriever
three   8   3  bird             Robin
-1     22   5   dog          Bulldog 
10      6  10   cat            Bengal
10      5   4  fish          Bluefish

Sorting a dataframe by values of a particular column


In [108]:
df2.sort_values(by="C") # returns a copy

A   B     C                 D
three   8   3  bird             Robin
11      2   2   cat           Ragdoll
10      6  10   cat            Bengal
12      2  -1   dog  Golden Retriever
-1     22   5   dog          Bulldog 
10      5   4  fish          Bluefish

Dropping a column


In [109]:
df2.drop("D", axis=1) # returns a copy. use inplace argument to modify df2

A   B     C
11      2   2   cat
12      2  -1   dog
three   8   3  bird
-1     22   5   dog
10      6  10   cat
10      5   4  fish

In [110]:
# checking the original dataframe if the dropped column is still in it
df2

A   B     C                 D
11      2   2   cat           Ragdoll
12      2  -1   dog  Golden Retriever
three   8   3  bird             Robin
-1     22   5   dog          Bulldog 
10      6  10   cat            Bengal
10      5   4  fish          Bluefish

Dropping a row


In [111]:
df2.drop(12, axis=0) # returns a copy

A   B     C         D
11      2   2   cat   Ragdoll
three   8   3  bird     Robin
-1     22   5   dog  Bulldog 
10      6  10   cat    Bengal
10      5   4  fish  Bluefish

Logical filtering operators

`~` = `not`  
`&` = `and`  
`|` = `or`

Using the not operator '~' for filtering all rows that don't have the value 'cat' for the 'C' column.


In [112]:
df2[~(df2["C"] == "cat")]

A  B     C                 D
12      2 -1   dog  Golden Retriever
three   8  3  bird             Robin
-1     22  5   dog          Bulldog 
10      5  4  fish          Bluefish

Filtering by multiple conditions


In [113]:
# using logical AND to filter all rows where the value of 'C' column is 'cat' AND the value of 'D' column is 'Ragdoll'
df2[(df2["C"] == "cat") & (df2['D'] == "Ragdoll")]

A  B    C        D
11  2  2  cat  Ragdoll

In [114]:
# using logical OR to filter all rows where the value of 'C' column is 'cat' OR the value of 'A' column is 2
df2[(df2["C"] == "cat") | (df2['A'] == 2)]

A   B    C                 D
11  2   2  cat           Ragdoll
12  2  -1  dog  Golden Retriever
10  6  10  cat            Bengal

Index of a dataframe can have duplicated indexes. For example, `df2` has two rows with index 10 as shwon below:

In [115]:
df2

A   B     C                 D
11      2   2   cat           Ragdoll
12      2  -1   dog  Golden Retriever
three   8   3  bird             Robin
-1     22   5   dog          Bulldog 
10      6  10   cat            Bengal
10      5   4  fish          Bluefish

Selecting all rows with index 10 will therefore return a dataframe

In [116]:
df2.loc[10]

A   B     C         D
10  6  10   cat    Bengal
10  5   4  fish  Bluefish

Filtering using `.loc`


In [117]:
df2.loc[df2["A"] == 22]

A  B    C         D
-1  22  5  dog  Bulldog

Modifying the values of a subset of the data using .loc in conjunction with boolean series


In [118]:
df2.loc[df2["A"] == 22] = 10
df2

A   B     C                 D
11      2   2   cat           Ragdoll
12      2  -1   dog  Golden Retriever
three   8   3  bird             Robin
-1     10  10    10                10
10      6  10   cat            Bengal
10      5   4  fish          Bluefish

In [119]:
df2.loc[df2["A"] == 10, "C"] = "dog"
df2

A   B     C                 D
11      2   2   cat           Ragdoll
12      2  -1   dog  Golden Retriever
three   8   3  bird             Robin
-1     10  10   dog                10
10      6  10   cat            Bengal
10      5   4  fish          Bluefish

Using iloc with DataFrames works like using loc except that it is the integer indexed. Try it out yourself

Unique values in a column

In [120]:
df2['C'].unique()

array(['cat', 'dog', 'bird', 'fish'], dtype=object)

#### Working with External Data

Loading Data

Titanic data gotten from: [Kaggle](https://www.kaggle.com/competitions/titanic/data)

Loading in a csv file


In [121]:
titanic_df = pd.read_csv("https://raw.githubusercontent.com/MIE223-2024/course-datasets/main/titanic_train.csv")

print(titanic_df.shape)
titanic_df.head() # by default, it displays the first 5 rows

(891, 12)


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [122]:
titanic_df.head(10) # displaying the first 10 rows

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [123]:
titanic_df.tail() # display the last five rows

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

Count of non-null rows per column

In [124]:
titanic_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

 Checking the number of unique values per column

In [125]:
titanic_df.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

Count of unique values in a particular column


In [126]:
titanic_df["Sex"].value_counts()

male      577
female    314
Name: Sex, dtype: int64

Summary stats for continuous variables. By default, `.describe` method of a DataFrame computes summary statistics for only columns with continuous values.

In [127]:
titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

Summary stats for all variables (continuous and discrete). Notice what the summary statistics for the discrete variables are.

In [128]:
titanic_df.describe(include='all')

PassengerId    Survived      Pclass                     Name   Sex  \
count    891.000000  891.000000  891.000000                      891   891   
unique          NaN         NaN         NaN                      891     2   
top             NaN         NaN         NaN  Braund, Mr. Owen Harris  male   
freq            NaN         NaN         NaN                        1   577   
mean     446.000000    0.383838    2.308642                      NaN   NaN   
std      257.353842    0.486592    0.836071                      NaN   NaN   
min        1.000000    0.000000    1.000000                      NaN   NaN   
25%      223.500000    0.000000    2.000000                      NaN   NaN   
50%      446.000000    0.000000    3.000000                      NaN   NaN   
75%      668.500000    1.000000    3.000000                      NaN   NaN   
max      891.000000    1.000000    3.000000                      NaN   NaN   

               Age       SibSp       Parch  Ticket        Fare    Cabin  \
count   714.000000  891.000000  891.000000     891  891.000000      204   
unique         NaN         NaN         NaN     681         NaN      147   
top            NaN         NaN         NaN  347082         NaN  B96 B98   
freq           NaN         NaN         NaN       7         NaN        4   
mean     29.699118    0.523008    0.381594     NaN   32.204208      NaN   
std      14.526497    1.102743    0.806057     NaN   49.693429      NaN   
min       0.420000    0.000000    0.000000     NaN    0.000000      NaN   
25%      20.125000    0.000000    0.000000     NaN    7.910400      NaN   
50%      28.000000    0.000000    0.000000     NaN   14.454200      NaN   
75%      38.000000    1.000000    0.000000     NaN   31.000000      NaN   
max      80.000000    8.000000    6.000000     NaN  512.329200      NaN   

       Embarked  
count       889  
unique        3  
top           S  
freq        644  
mean        NaN  
std         NaN  
min         NaN  
25%         NaN  
50%         NaN  
75%         NaN  
max         NaN

Checking summary statistics for a particlular column in the data.


In [129]:
titanic_df['Age'].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

Checking for null values. What are null values? They are placeholders for values that are missing.


In [130]:
titanic_df.isnull().head()

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0        False     False   False  False  False  False  False  False   False   
1        False     False   False  False  False  False  False  False   False   
2        False     False   False  False  False  False  False  False   False   
3        False     False   False  False  False  False  False  False   False   
4        False     False   False  False  False  False  False  False   False   

    Fare  Cabin  Embarked  
0  False   True     False  
1  False  False     False  
2  False   True     False  
3  False  False     False  
4  False   True     False

Null values count per column

In [131]:
titanic_df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Null values count per row

In [132]:
titanic_df.isnull().sum(axis=1).head(15)

0     1
1     0
2     1
3     0
4     1
5     2
6     0
7     1
8     1
9     1
10    0
11    0
12    1
13    1
14    1
dtype: int64

Total number of missing values in the data. You can chain functions in pandas, this is one if its strengths!

In [133]:
titanic_df.isnull().sum().sum()

866

Handling Missing Values.

We need to know reason for missingness. How do we handle missing values? Imputation? or Dropping them? If we are to drop them, do we drop rows? or columns?

If you know the reason for missingness in a feature, or if the number of missing values in a feature is low, you can impute them (replace the missing values). How? If continuous: mean?, or median? Nearest Neigbours? If categorical: Mode? Be careful, imputation can change the distribution of a data.

If the percentage of missing values in a row or column is high, you may want to drop the row or column as the case may be.


Finding percentage of missing values per feature

In [134]:
titanic_df.isnull().sum() / titanic_df.shape[0]

PassengerId    0.000000
Survived       0.000000
Pclass         0.000000
Name           0.000000
Sex            0.000000
Age            0.198653
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
Cabin          0.771044
Embarked       0.002245
dtype: float64

If we were to build an ML model, we may want to drop "Cabin" column because it has many missing values.

Checking the data type per column. We need to know this to know which column(s) are continuous or discrete.

In [135]:
titanic_df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

Handling missing values


In [136]:
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean()) # replacing missing values in 'Age' column with the mean because its values are continuous
titanic_df['Embarked'] = titanic_df['Embarked'].fillna(titanic_df['Embarked'].mode()[0]) # replacing missing values in 'Embarked' column with the mode because its values are discrete
titanic_df.drop("Cabin", axis=1, inplace=True) # dropping the 'Cabin' column because it has many missing values
titanic_df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

Working with strings


Checking all rows in the `'Name'` column that contains the word 'james'  regardless of case.

In [137]:
titanic_df[titanic_df['Name'].str.contains("james", case=False)]['Name']

5                                       Moran, Mr. James
67                              Crease, Mr. Ernest James
134                       Sobey, Mr. Samuel James Hayden
150                           Bateman, Rev. Robert James
161    Watt, Mrs. James (Elizabeth "Bessie" Inglis Mi...
174                              Smith, Mr. James Clinch
194            Brown, Mrs. James Joseph (Margaret Tobin)
221                                 Bracken, Mr. James H
250                               Reed, Mr. James George
299      Baxter, Mrs. James (Helene DeLaudeniere Chaput)
416      Drew, Mrs. James Vivian (Lulu Thorne Christian)
428                                     Flynn, Mr. James
468                                   Scanlan, Mr. James
511                                    Webber, Mr. James
512                            McGough, Mr. James Robert
525                                   Farrell, Mr. James
551                          Sharp, Mr. Percival James R
582                           D

You can modify a DataFrame by assigning it to a modified copy e.g setting its index.

In [138]:
titanic_df = titanic_df.set_index("PassengerId") # setting 'PassengerId' as the index
titanic_df.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Embarked  
PassengerId                                                    
1                1      0         A/5 21171   7.2500        S  
2                1      0          PC 17599  71.2833        C  
3                0      0  STON/O2. 3101282   7.9250        S  
4                1      0            113803  53.1000        S  
5                0      0            373450   8.0500        S

You can also use `inplace=True` to modify a DataFrame instead of re-assigning it to a modified copy. Demonstrating this using the `.reset_index` method of a DataFrame.

In [139]:
titanic_df.reset_index(inplace=True) # resetting the index
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Embarked  
0      0         A/5 21171   7.2500        S  
1      0          PC 17599  71.2833        C  
2      0  STON/O2. 3101282   7.9250        S  
3      0            113803  53.1000        S  
4      0            373450   8.0500        S

Setting `PassengerId` back as the index because we want to use it as the id for each row.

In [140]:
titanic_df.set_index("PassengerId", inplace=True)
titanic_df.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Embarked  
PassengerId                                                    
1                1      0         A/5 21171   7.2500        S  
2                1      0          PC 17599  71.2833        C  
3                0      0  STON/O2. 3101282   7.9250        S  
4                1      0            113803  53.1000        S  
5                0      0            373450   8.0500        S

Renaming a column


In [141]:
titanic_df = titanic_df.rename({"Name": "FullName"}, axis=1)
titanic_df.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                      FullName     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Embarked  
PassengerId                                                    
1                1      0         A/5 21171   7.2500        S  
2                1      0          PC 17599  71.2833        C  
3                0      0  STON/O2. 3101282   7.9250        S  
4                1      0            113803  53.1000        S  
5                0      0            373450   8.0500        S

Checking the unique values in 'Embarked' column.

In [142]:
titanic_df['Embarked'].unique()

array(['S', 'C', 'Q'], dtype=object)

The [metadata](https://www.kaggle.com/competitions/titanic/data#:~:text=should%20look%20like.-,Data%20Dictionary,-Variable) for the datasets on kaggle shows that the values in the 'Embarked' column are abbreviations for the port of departure. We may want to replace them with the actual port names. To do this we need to **transform** the 'Embarked' column.

#### Transformation functions

Defining a function to return the full form for a given short-form for values in `'Embarked'` column.


In [143]:
def get_port_of_embarkment(embarked: str) -> str:
    ports = {"C": "Cherbourg", "Q": "Queenstown", "S": "Southampton"}

    return ports.get(embarked, None)

Using `.apply` to apply `get_port_of_embarkment` function to each row in the `Embarked` column.


In [144]:
titanic_df['Embarked'] = titanic_df['Embarked'].apply(get_port_of_embarkment)
titanic_df.head(10)

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
6                   0       3   
7                   0       1   
8                   0       3   
9                   1       3   
10                  1       2   

                                                      FullName     Sex  \
PassengerId                                                              
1                                      Braund, Mr. Owen Harris    male   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
3                                       Heikkinen, Miss. Laina  female   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
5                                     Allen, Mr. William Henry    male   
6                                             Moran, Mr. James    male   
7                                      McCarthy, Mr. Timothy J    male   
8                               Palsson, Master. Gosta Leonard    male   
9            Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female   
10                         Nasser, Mrs. Nicholas (Adele Achem)  female   

                   Age  SibSp  Parch            Ticket     Fare     Embarked  
PassengerId                                                                   
1            22.000000      1      0         A/5 21171   7.2500  Southampton  
2            38.000000      1      0          PC 17599  71.2833    Cherbourg  
3            26.000000      0      0  STON/O2. 3101282   7.9250  Southampton  
4            35.000000      1      0            113803  53.1000  Southampton  
5            35.000000      0      0            373450   8.0500  Southampton  
6            29.699118      0      0            330877   8.4583   Queenstown  
7            54.000000      0      0             17463  51.8625  Southampton  
8             2.000000      3      1            349909  21.0750  Southampton  
9            27.000000      0      2            347742  11.1333  Southampton  
10           14.000000      1      0            237736  30.0708    Cherbourg

You can also use lambda functions. Note: `.apply` can also be applied to an entire row in a dataframe, you just have to define your function appropriately.


The [metadata](https://www.kaggle.com/competitions/titanic/data#:~:text=should%20look%20like.-,Data%20Dictionary,-Variable) for the datasets on kaggle shows that the values in the 'Survived' column are 1 when passengers survived, and 0 otherwise. We can use **lambda functions to transform** the 'Survived' column to 'Yes' if a passenger survived, and 'No' if he/she doesn't survive.

In [145]:
titanic_df.apply(lambda x: "Yes" if x["Survived"] == 1 else "No", axis=1).head(10)

PassengerId
1      No
2     Yes
3     Yes
4     Yes
5      No
6      No
7      No
8      No
9     Yes
10    Yes
dtype: object

#### Groupby

Groupby = split + aggregate + combine

In [146]:
groups = titanic_df.groupby("Sex")
list(groups.groups['female'])[:10] # .groups returns a dictionary of group name / index pairs

[2, 3, 4, 9, 10, 11, 12, 15, 16, 19]

In [147]:
groups.get_group('female').head() # .get_group returns the dataframe corresponding to the group.

Survived  Pclass  \
PassengerId                     
2                   1       1   
3                   1       3   
4                   1       1   
9                   1       3   
10                  1       2   

                                                      FullName     Sex   Age  \
PassengerId                                                                    
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
9            Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   
10                         Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   

             SibSp  Parch            Ticket     Fare     Embarked  
PassengerId                                                        
2                1      0          PC 17599  71.2833    Cherbourg  
3                0      0  STON/O2. 3101282   7.9250  Southampton  
4                1      0            113803  53.1000  Southampton  
9                0      2            347742  11.1333  Southampton  
10               1      0            237736  30.0708    Cherbourg

Using groupby to return the count per unique categories in the 'sex' column


In [148]:
titanic_df.groupby("Sex")["FullName"].count()

Sex
female    314
male      577
Name: FullName, dtype: int64

The code below gives the same result as above. Can you explain why?


In [149]:
titanic_df.groupby("Sex").count()["FullName"]

Sex
female    314
male      577
Name: FullName, dtype: int64

Using `.agg` to apply different aggregation functions to different columns of a DataFrame during `groupby`.

In [150]:
titanic_df.groupby("Survived").agg({"Age": "mean", "Fare": "max"})

Age      Fare
Survived                     
0         30.415100  263.0000
1         28.549778  512.3292

Renaming the returned columns in the agg function: we can also use `.agg` function to rename the columns of the resulting DataFrame after applying grouby.


In [151]:
titanic_df.groupby("Survived").agg(avg_age=("Age", "mean"), max_age=("Age", "max"), avg_fare=("Fare", "mean"), max_fare=("Fare", "max"))

avg_age  max_age   avg_fare  max_fare
Survived                                         
0         30.415100     74.0  22.117887  263.0000
1         28.549778     80.0  48.395408  512.3292

Finding the mean fare price for each `Pclass` for each `Embarked`. What are long data formats?


In [152]:
titanic_df_long = titanic_df.groupby(["Embarked", "Pclass"])["Fare"].mean()
titanic_df_long

Embarked     Pclass
Cherbourg    1         104.718529
             2          25.358335
             3          11.214083
Queenstown   1          90.000000
             2          12.350000
             3          11.183393
Southampton  1          70.514244
             2          20.327439
             3          14.644083
Name: Fare, dtype: float64

Long data format: each subject ('Embarked') in this case will have data in multiple rows. One for each response ('Pclass').

Notice that the index aren't sequential as before We can use `.reset_index()` to reset the index after applying groupby.

In [153]:
titanic_df_long = titanic_df.groupby(["Embarked", "Pclass"])["Fare"].mean().reset_index()
titanic_df_long

Embarked  Pclass        Fare
0    Cherbourg       1  104.718529
1    Cherbourg       2   25.358335
2    Cherbourg       3   11.214083
3   Queenstown       1   90.000000
4   Queenstown       2   12.350000
5   Queenstown       3   11.183393
6  Southampton       1   70.514244
7  Southampton       2   20.327439
8  Southampton       3   14.644083

Wide data format: a subject's ('Embarked') repeated responses will be in a single row, and each response ('Pclass') is in a separate column.


In [154]:
titanic_df_wide = titanic_df_long.pivot(index="Embarked", columns="Pclass", values="Fare")
titanic_df_wide

Pclass                1          2          3
Embarked                                     
Cherbourg    104.718529  25.358335  11.214083
Queenstown    90.000000  12.350000  11.183393
Southampton   70.514244  20.327439  14.644083

## (OPTIONAL): Extra Topics (will not be part of assignment and quiz).

#### Joining Data

In [155]:
# loading in the test data
titanic_df_test = pd.read_csv("https://raw.githubusercontent.com/MIE223-2024/course-datasets/main/titanic_test.csv")
print(titanic_df_test.shape)
titanic_df_test.head()

(418, 11)


PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

##### Concatenating

In [156]:
# preparing the data like we did for the training data

titanic_df_test.set_index("PassengerId", inplace=True)
titanic_df_test['Embarked'] = titanic_df_test['Embarked'].apply(get_port_of_embarkment)
titanic_df_test.head(10)

Pclass                                          Name     Sex  \
PassengerId                                                                 
892               3                              Kelly, Mr. James    male   
893               3              Wilkes, Mrs. James (Ellen Needs)  female   
894               2                     Myles, Mr. Thomas Francis    male   
895               3                              Wirz, Mr. Albert    male   
896               3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   
897               3                    Svensson, Mr. Johan Cervin    male   
898               3                          Connolly, Miss. Kate  female   
899               2                  Caldwell, Mr. Albert Francis    male   
900               3     Abrahim, Mrs. Joseph (Sophie Halaut Easu)  female   
901               3                       Davies, Mr. John Samuel    male   

              Age  SibSp  Parch     Ticket     Fare Cabin     Embarked  
PassengerId                                                             
892          34.5      0      0     330911   7.8292   NaN   Queenstown  
893          47.0      1      0     363272   7.0000   NaN  Southampton  
894          62.0      0      0     240276   9.6875   NaN   Queenstown  
895          27.0      0      0     315154   8.6625   NaN  Southampton  
896          22.0      1      1    3101298  12.2875   NaN  Southampton  
897          14.0      0      0       7538   9.2250   NaN  Southampton  
898          30.0      0      0     330972   7.6292   NaN   Queenstown  
899          26.0      1      1     248738  29.0000   NaN  Southampton  
900          18.0      0      0       2657   7.2292   NaN    Cherbourg  
901          21.0      2      0  A/4 48871  24.1500   NaN  Southampton

In [157]:
# making a copy of train data
titanic_df_train = titanic_df.copy()
titanic_df_train.drop("Survived", axis=1, inplace=True) # so train and test will have the same number of columns
print(titanic_df_train.shape)
titanic_df_train.head()

(891, 9)


Pclass                                           FullName  \
PassengerId                                                              
1                 3                            Braund, Mr. Owen Harris   
2                 1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
3                 3                             Heikkinen, Miss. Laina   
4                 1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
5                 3                           Allen, Mr. William Henry   

                Sex   Age  SibSp  Parch            Ticket     Fare  \
PassengerId                                                          
1              male  22.0      1      0         A/5 21171   7.2500   
2            female  38.0      1      0          PC 17599  71.2833   
3            female  26.0      0      0  STON/O2. 3101282   7.9250   
4            female  35.0      1      0            113803  53.1000   
5              male  35.0      0      0            373450   8.0500   

                Embarked  
PassengerId               
1            Southampton  
2              Cherbourg  
3            Southampton  
4            Southampton  
5            Southampton

Concatenating train and test data vertically.

In [158]:
pd.concat([titanic_df_train, titanic_df_test]).head()

Pclass                                           FullName  \
PassengerId                                                              
1                 3                            Braund, Mr. Owen Harris   
2                 1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
3                 3                             Heikkinen, Miss. Laina   
4                 1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
5                 3                           Allen, Mr. William Henry   

                Sex   Age  SibSp  Parch            Ticket     Fare  \
PassengerId                                                          
1              male  22.0      1      0         A/5 21171   7.2500   
2            female  38.0      1      0          PC 17599  71.2833   
3            female  26.0      0      0  STON/O2. 3101282   7.9250   
4            female  35.0      1      0            113803  53.1000   
5              male  35.0      0      0            373450   8.0500   

                Embarked Name Cabin  
PassengerId                          
1            Southampton  NaN   NaN  
2              Cherbourg  NaN   NaN  
3            Southampton  NaN   NaN  
4            Southampton  NaN   NaN  
5            Southampton  NaN   NaN

Notice the extra column "Name". That is because the column names do not match. Also, `Cabin` was dropped in titanic_df_train, but not in titanic_df_test. So, know that you may have unexpected results if columns don't match in the dataframes.


In [159]:
# making the column names to match
titanic_df_test = titanic_df_test.rename(columns={"Name": "FullName"}) # renaming 'Name' column
titanic_df_test.drop("Cabin", axis=1, inplace=True) # dropping 'Cabin' column
titanic_df_test.head()

Pclass                                      FullName     Sex  \
PassengerId                                                                 
892               3                              Kelly, Mr. James    male   
893               3              Wilkes, Mrs. James (Ellen Needs)  female   
894               2                     Myles, Mr. Thomas Francis    male   
895               3                              Wirz, Mr. Albert    male   
896               3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

              Age  SibSp  Parch   Ticket     Fare     Embarked  
PassengerId                                                     
892          34.5      0      0   330911   7.8292   Queenstown  
893          47.0      1      0   363272   7.0000  Southampton  
894          62.0      0      0   240276   9.6875   Queenstown  
895          27.0      0      0   315154   8.6625  Southampton  
896          22.0      1      1  3101298  12.2875  Southampton

In [160]:
titanic_df_complete = pd.concat([titanic_df_train, titanic_df_test]) # to concatenate horizontally, set axis=1, in that case, dataframe indices are expected to match
print(titanic_df_complete.shape)
titanic_df_complete.head()

(1309, 9)


Pclass                                           FullName  \
PassengerId                                                              
1                 3                            Braund, Mr. Owen Harris   
2                 1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
3                 3                             Heikkinen, Miss. Laina   
4                 1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
5                 3                           Allen, Mr. William Henry   

                Sex   Age  SibSp  Parch            Ticket     Fare  \
PassengerId                                                          
1              male  22.0      1      0         A/5 21171   7.2500   
2            female  38.0      1      0          PC 17599  71.2833   
3            female  26.0      0      0  STON/O2. 3101282   7.9250   
4            female  35.0      1      0            113803  53.1000   
5              male  35.0      0      0            373450   8.0500   

                Embarked  
PassengerId               
1            Southampton  
2              Cherbourg  
3            Southampton  
4            Southampton  
5            Southampton

Pandas has an extensive [documentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html#database-style-dataframe-or-named-series-joining-merging) on joins.

![here](https://i0.wp.com/vitalflux.com/wp-content/uploads/2023/01/SQL-Joins-explained-using-Sets.png?ssl=1).

In [161]:
class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args

    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)

    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

Creating sample array


In [162]:
projects_arr = np.array([[100, 101, 102, 104, 103, 100, 102, 104, 100], [1001, 1001, 1001, 1001, 1002, 1002, 1003, 1003, 1003]]).T
projects_arr

array([[ 100, 1001],
       [ 101, 1001],
       [ 102, 1001],
       [ 104, 1001],
       [ 103, 1002],
       [ 100, 1002],
       [ 102, 1003],
       [ 104, 1003],
       [ 100, 1003]])

Creating sample dataframes to demonstrate join


In [163]:
employee_df = pd.DataFrame({'id': [100, 101, 102, 103, 104, 105],
                    'name': ['Bob', 'Jake', 'Rose', 'Sandra', 'Joe', 'Lisa'],
                    'department': ['Risk', 'Data Science', 'Data Science', 'Marketing', 'Marketing', 'Data Science']
                    }
                   )

projects_df = pd.DataFrame(
    [
        [1001, 'in progress'],
         [1002, 'blocked'],
          [1003, 'completed'],
            [1110, 'in progress'] # project outsourced
        ], columns=['project_id', 'project_status']
    )

project_members_df = pd.DataFrame(projects_arr)
project_members_df.columns = ['employee_id', 'project_id']

display('employee_df', 'project_members_df')

employee_df
    id    name    department
0  100     Bob          Risk
1  101    Jake  Data Science
2  102    Rose  Data Science
3  103  Sandra     Marketing
4  104     Joe     Marketing
5  105    Lisa  Data Science

project_members_df
   employee_id  project_id
0          100        1001
1          101        1001
2          102        1001
3          104        1001
4          103        1002
5          100        1002
6          102        1003
7          104        1003
8          100        1003

##### Inner Join


In [164]:
df = pd.merge(project_members_df, employee_df, left_on="employee_id", right_on="id", how="inner") # default 'how' is inner join
display('employee_df', 'project_members_df', 'df')

employee_df
    id    name    department
0  100     Bob          Risk
1  101    Jake  Data Science
2  102    Rose  Data Science
3  103  Sandra     Marketing
4  104     Joe     Marketing
5  105    Lisa  Data Science

project_members_df
   employee_id  project_id
0          100        1001
1          101        1001
2          102        1001
3          104        1001
4          103        1002
5          100        1002
6          102        1003
7          104        1003
8          100        1003

df
   employee_id  project_id   id    name    department
0          100        1001  100     Bob          Risk
1          100        1002  100     Bob          Risk
2          100        1003  100     Bob          Risk
3          101        1001  101    Jake  Data Science
4          102        1001  102    Rose  Data Science
5          102        1003  102    Rose  Data Science
6          104        1001  104     Joe     Marketing
7          104        1003  104     Joe     Marketing
8          103        1002  103  Sandra     Marketing

##### Left Join


In [165]:
df = pd.merge(employee_df, project_members_df, left_on="id", right_on="employee_id", how="left")
display('employee_df', 'project_members_df', 'df')

employee_df
    id    name    department
0  100     Bob          Risk
1  101    Jake  Data Science
2  102    Rose  Data Science
3  103  Sandra     Marketing
4  104     Joe     Marketing
5  105    Lisa  Data Science

project_members_df
   employee_id  project_id
0          100        1001
1          101        1001
2          102        1001
3          104        1001
4          103        1002
5          100        1002
6          102        1003
7          104        1003
8          100        1003

df
    id    name    department  employee_id  project_id
0  100     Bob          Risk        100.0      1001.0
1  100     Bob          Risk        100.0      1002.0
2  100     Bob          Risk        100.0      1003.0
3  101    Jake  Data Science        101.0      1001.0
4  102    Rose  Data Science        102.0      1001.0
5  102    Rose  Data Science        102.0      1003.0
6  103  Sandra     Marketing        103.0      1002.0
7  104     Joe     Marketing        104.0      1001.0
8  104     Joe     Marketing        104.0      1003.0
9  105    Lisa  Data Science          NaN         NaN

##### Right Join


Right join is similar to left join. Only that all rows in the right table are returned whether they have a match or not.

In [166]:
complete_project_members_df = pd.merge(project_members_df, projects_df, on="project_id", how='right')
display('project_members_df', 'projects_df', 'complete_project_members_df')

project_members_df
   employee_id  project_id
0          100        1001
1          101        1001
2          102        1001
3          104        1001
4          103        1002
5          100        1002
6          102        1003
7          104        1003
8          100        1003

projects_df
   project_id project_status
0        1001    in progress
1        1002        blocked
2        1003      completed
3        1110    in progress

complete_project_members_df
   employee_id  project_id project_status
0        100.0        1001    in progress
1        101.0        1001    in progress
2        102.0        1001    in progress
3        104.0        1001    in progress
4        103.0        1002        blocked
5        100.0        1002        blocked
6        102.0        1003      completed
7        104.0        1003      completed
8        100.0        1003      completed
9          NaN        1110    in progress

##### Outer Join


In [167]:
df = pd.merge(employee_df, complete_project_members_df, left_on="id", right_on="employee_id", how="outer")
display('employee_df', 'complete_project_members_df', 'df')

employee_df
    id    name    department
0  100     Bob          Risk
1  101    Jake  Data Science
2  102    Rose  Data Science
3  103  Sandra     Marketing
4  104     Joe     Marketing
5  105    Lisa  Data Science

complete_project_members_df
   employee_id  project_id project_status
0        100.0        1001    in progress
1        101.0        1001    in progress
2        102.0        1001    in progress
3        104.0        1001    in progress
4        103.0        1002        blocked
5        100.0        1002        blocked
6        102.0        1003      completed
7        104.0        1003      completed
8        100.0        1003      completed
9          NaN        1110    in progress

df
       id    name    department  employee_id  project_id project_status
0   100.0     Bob          Risk        100.0      1001.0    in progress
1   100.0     Bob          Risk        100.0      1002.0        blocked
2   100.0     Bob          Risk        100.0      1003.0      completed
3   101.0    Jake  Data Science        101.0      1001.0    in progress
4   102.0    Rose  Data Science        102.0      1001.0    in progress
5   102.0    Rose  Data Science        102.0      1003.0      completed
6   103.0  Sandra     Marketing        103.0      1002.0        blocked
7   104.0     Joe     Marketing        104.0      1001.0    in progress
8   104.0     Joe     Marketing        104.0      1003.0      completed
9   105.0    Lisa  Data Science          NaN         NaN            NaN
10    NaN     NaN           NaN          NaN      1110.0    in progress

There are a lot of useful functions in pandas that we do not have enough time to cover, we strongly encourage you to read their documentations for reference.

https://pandas.pydata.org/docs/